const process = require('process')

const NODE_ENV = process.env.NODE_ENV

const PORT = process.env.PORT || 8080
const DB_CONNECTION_STRING = process.env.DB_CONNECTION_STRING
const SESSION_SECRET = process.env.SESSION_SECRET

const TWITTER_TOKEN = process.env.TWITTER_TOKEN
const TWITTER_TOKEN_SECRET = process.env.TWITTER_TOKEN_SECRET
const TWITTER_CONSUMER_KEY = process.env.TWITTER_CONSUMER_KEY
const TWITTER_CONSUMER_SECRET = process.env.TWITTER_CONSUMER_SECRET
const TWITTER_BEARER_TOKEN = process.env.TWITTER_BEARER_TOKEN

const CALLBACK_URL = process.env.CALLBACK_URL
const ORIGIN_URL = process.env.ORIGIN_URL.split(', ')

module.exports = {
  NODE_ENV,

  PORT,
  DB_CONNECTION_STRING,
  SESSION_SECRET,

  TWITTER_TOKEN,
  TWITTER_TOKEN_SECRET,
  TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET,
  TWITTER_BEARER_TOKEN, 
  CALLBACK_URL,
  ORIGIN_URL,
}
